function Auxiliary.PreloadUds()
	local e1=Effect.GlobalEffect()
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_ADJUST)
	e1:SetOperation(function(e)
		for tp=0,1 do
			for i=1,3 do
				local tc=Duel.CreateToken(tp,46565218)
				Duel.SendtoDeck(tc,nil,2,REASON_RULE)
			end
			local tc=Duel.CreateToken(tp,46565218)
			Duel.SendtoHand(tc,nil,REASON_RULE)
			local function atkfilter(c,atk,no_attack_check)
				return c:IsFaceup() and c:IsAttackAbove(atk) and not c:IsHasEffect(EFFECT_REVERSE_UPDATE) and (no_attack_check or c:GetAttackAnnouncedCount()==0)
			end
			function con(atk,conf,no_attack_check)
				return function(e,tp,eg,ep,ev,re,r,rp)
					return Duel.GetTurnPlayer()==tp and Duel.GetCurrentChain()==0 and (Duel.GetCurrentPhase()&(PHASE_MAIN1|PHASE_MAIN2))>0 and Duel.IsExistingMatchingCard(atkfilter,tp,LOCATION_MZONE,0,1,nil,atk,no_attack_check) and (not conf or conf(e,tp,eg,ep,ev,re,r,rp))
				end
			end
			function op(atk,opf,no_attack_check)
				return function(e,tp,eg,ep,ev,re,r,rp)
					Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SELF)
					local g=Duel.SelectMatchingCard(tp,atkfilter,tp,LOCATION_MZONE,0,1,1,nil,atk,no_attack_check)
					local tc=g:GetFirst()
					local ex=Effect.CreateEffect(e:GetOwner())
					ex:SetType(EFFECT_TYPE_SINGLE)
					ex:SetCode(EFFECT_UPDATE_ATTACK)
					ex:SetValue(-atk)
					ex:SetReset(0x1fe1000)
					tc:RegisterEffect(ex,true)
					Duel.Hint(HINT_CARD,0,46565218)
					Duel.Hint(HINT_OPSELECTED,1-tp,e:GetDescription())
					opf(e,tp,eg,ep,ev,re,r,rp)
				end
			end
			for tp=0,1 do
				local e1=Effect.CreateEffect(tc)
				e1:SetDescription(1108)
				e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e1:SetCountLimit(1,10000001)
				e1:SetCode(EVENT_FREE_CHAIN)
				e1:SetCondition(con(2020,function(e,tp,eg,ep,ev,re,r,rp)
					return Duel.IsPlayerCanDraw(tp,1)
				end))
				e1:SetOperation(op(2020,function(e,tp,eg,ep,ev,re,r,rp)
					Duel.Draw(tp,1,REASON_EFFECT)
				end))
				Duel.RegisterEffect(e1,tp)
				local e1=Effect.CreateEffect(tc)
				e1:SetDescription(1113)
				e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e1:SetCountLimit(1,10000001)
				e1:SetCode(EVENT_FREE_CHAIN)
				e1:SetCondition(con(2020,function(e,tp,eg,ep,ev,re,r,rp)
					return Duel.IsExistingMatchingCard(Card.IsFaceup,tp,0,LOCATION_MZONE,1,nil)
				end))
				e1:SetOperation(op(2020,function(e,tp,eg,ep,ev,re,r,rp)
					Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_OPPO)
					local g=Duel.SelectMatchingCard(tp,Card.IsFaceup,tp,0,LOCATION_MZONE,1,2,nil)
					for tc in aux.Next(g) do
						local ex=Effect.CreateEffect(e:GetOwner())
						ex:SetType(EFFECT_TYPE_SINGLE)
						ex:SetCode(EFFECT_UPDATE_ATTACK)
						ex:SetValue(-2020)
						ex:SetReset(0x1fe1000)
						tc:RegisterEffect(ex)
					end
				end))
				Duel.RegisterEffect(e1,tp)
				local e1=Effect.CreateEffect(tc)
				e1:SetDescription(1122)
				e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e1:SetCountLimit(1,10000001)
				e1:SetCode(EVENT_FREE_CHAIN)
				e1:SetCondition(con(1225,function(e,tp,eg,ep,ev,re,r,rp)
					return true
				end,true))
				e1:SetOperation(op(1225,function(e,tp,eg,ep,ev,re,r,rp)
					Duel.SetLP(1-tp,math.max(Duel.GetLP(1-tp)-400,0))
				end,true))
				Duel.RegisterEffect(e1,tp)
				local e1=Effect.CreateEffect(tc)
				e1:SetDescription(1123)
				e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
				e1:SetCountLimit(1,10000001)
				e1:SetCode(EVENT_FREE_CHAIN)
				e1:SetCondition(con(1225,function(e,tp,eg,ep,ev,re,r,rp)
					return true
				end))
				e1:SetOperation(op(1225,function(e,tp,eg,ep,ev,re,r,rp)
					Duel.SetLP(tp,Duel.GetLP(tp)+2020)
				end))
				Duel.RegisterEffect(e1,tp)
			end
		end
		e:Reset()
	end)
	Duel.RegisterEffect(e1,0)
end
