function Auxiliary.PreloadUds()
	local ex=Effect.GlobalEffect()
	ex:SetType(EFFECT_TYPE_FIELD)
	ex:SetCode(EFFECT_SKIP_DP)
	ex:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ex:SetTargetRange(1,1)
	ex:SetCondition(function(e)
		return Duel.GetTurnCount()<8
	end)
	ex:SetValue(1)
	Duel.RegisterEffect(ex,0)
	local ex=Effect.GlobalEffect()
	ex:SetType(EFFECT_TYPE_FIELD)
	ex:SetCode(EFFECT_CANNOT_SUMMON)
	ex:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ex:SetTargetRange(1,1)
	ex:SetValue(1)
	Duel.RegisterEffect(ex,0)
	local ex=Effect.GlobalEffect()
	ex:SetType(EFFECT_TYPE_FIELD)
	ex:SetCode(EFFECT_CANNOT_MSET)
	ex:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ex:SetTargetRange(1,1)
	ex:SetValue(1)
	Duel.RegisterEffect(ex,0)
end
